package it.unibs.pajc.pokeproject.util;

public enum Commands {
	MSG_REMATCH_NO,
	MSG_REMATCH_YES,
	MSG_SELECTED_MOVE,
	MSG_SELECTED_POKEMON,
	MSG_DONE_DAMAGE,
	MSG_OPPONENT_MOVE,
	MSG_RECEIVED_DAMAGE,
	MSG_BATTLE_OVER,
	MSG_REMATCH,
	MSG_OPPONENT_POKEMON,
	MSG_START_BATTLE,
	MSG_WAITING,
	MSG_WAKEUP;
}