package it.unibs.pajc.pokeproject.util;

public enum Commands {
	MSG_TEST_CONNECTION,
	MSG_CONNECTION_CLOSED,
	MSG_SELECTED_POKEMON,
	MSG_PLAYER_FOUND,
	MSG_START_BATTLE,
	MSG_OPPONENT_POKEMON,
	MSG_SELECTED_MOVE,
	MSG_TURN,
	MSG_BATTLE_OVER,
	MSG_REMATCH,
	MSG_REMATCH_NO,
	MSG_REMATCH_YES;
}